---
abstract: 'The factory class for modules that retrieve'
author:
  - 'Guillaume Aubert <aubertg@cpan.org>'
build_requires:
  Carp: 0
  Class::Load: 0
  HTTP::Request: 0
  HTTP::Request::Common: 0
  LWP::UserAgent: 0
  Scalar::Util: 0
  Storable: 0
  Test::More: 0.94
  XML::LibXML: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.120530'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-CyberSource-Report
provides:
  Business::CyberSource::Report:
    file: lib/Business/CyberSource/Report.pm
    version: v1.1.2
  Business::CyberSource::Report::PaymentEvents:
    file: lib/Business/CyberSource/Report/PaymentEvents.pm
    version: v1.1.2
  Business::CyberSource::Report::SingleTransaction:
    file: lib/Business/CyberSource/Report/SingleTransaction.pm
    version: v1.1.2
requires:
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/NoAuth/ReportBug.html?Queue=business-cybersource-report
  homepage: https://metacpan.org/release/Business-CyberSource-Report
  license: http://opensource.org/licenses/artistic-license.php
  repository: https://sourceforge.net/p/cybersourceperl/code
version: v1.1.2
